### ISSUE TITLE
memes!

### ISSUE THREAD

**Issue by phellipeandrade** [anotherrandomdev/awesome-microsoft-memes#1]
https://pbs.twimg.com/media/Deze_3TVMAAubYw?format=jpg
https://pbs.twimg.com/media/De0E87IWkAIH9dT?format=jpg

**Comment by anotherrandomdev** [comment]
haha boa! consegue mandar como pull request? só editar o readme e jogar os arquivos no images/

**Comment by phellipeandrade** [comment]
Criei a branch mas não estou conseguindo enviar para abrir o PR, pode ajustar as permissões?

**Comment by anotherrandomdev** [comment]
opa, achei que ia fazer via fork, mas anyway, adicionei como collab.

**Comment by anotherrandomdev** [comment]
Done & Merged on #2
